WEBHOOK_PASSPHRASE = "INSERT PASSPHRASE HERE"

API_KEY = "INSERT KEY HERE"
API_SECRET = "INSERT KEY HERE"

REPORT = True

DISCORD_ERROR_ID = "INSERT CHANNEL ID"
DISCORD_TRANSACTION_ID = "INSERT CHANNEL ID"
DISCORD_ERROR_LINK = f"https://discord.com/api/v9/channels/{DISCORD_ERROR_ID}/messages"
DISCORD_TRANSACTION_LINK = f"https://discord.com/api/v9/channels/{DISCORD_TRANSACTION_ID}/messages"

DISCORD_HEADER = {"authorization": "INSERT AUTH ID"}

LEVERAGE = 0.9


LIMIT_DIFFERENCE = 0.0005
